[package]
name = "aoc"
version = "0.1.0"
authors = ["Scott Hutton <schutton@cisco.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
